# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
xcodeproj 'cnbeta'

pod 'Cb.framework', :path => '../core'

target 'cnbeta' do

end

target 'cnbetaTests' do

end

